# $NetBSD$

DISTNAME=	openssl-ccm-1.2.1
CATEGORIES=	security

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/smalllars/openssl-ccm
COMMENT=	Ruby Gem for RFC 3610 - Counter with CBC-MAC (CCM)
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
