# $NetBSD$

DISTNAME=	patch_finder-1.0.2
CATEGORIES=	security

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://github.com/wchen-r7/patch-finder
COMMENT=	Toolkit to find software patches
LICENSE=	modified-bsd

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
