# $NetBSD$

DISTNAME=	rex-registry-0.1.0
CATEGORIES=	security

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/rapid7/rex-registry
COMMENT=	Ruby Exploitation library for parsing Windows registry files

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
