# $NetBSD$

CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/r-lib/pkgconfig
COMMENT=	Private configuration for R packages
LICENSE=	mit

R_PKGNAME=	pkgconfig
R_PKGVER=	2.0.1

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
