# $NetBSD$

CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://mc-stan.org/
COMMENT=	C++ header files for Stan
LICENSE=	modified-bsd

R_PKGNAME=	StanHeaders
R_PKGVER=	2.17.2

USE_LANGUAGES=	c c++

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
