# $NetBSD$

CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://cran.r-project.org/package=BH
COMMENT=	Boost C++ header files
LICENSE=	boost-license

R_PKGNAME=	BH
R_PKGVER=	1.66.0-1

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
