# $NetBSD$

CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/krlmlr/plogr
COMMENT=	Simple header-only logging library for C++
LICENSE=	mit

R_PKGNAME=	plogr
R_PKGVER=	0.1-1

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
