# $NetBSD$

CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://cran.r-project.org/package=gridExtra
COMMENT=	Miscellaneous functions for "grid" graphics
LICENSE=	gnu-gpl-v2

R_PKGNAME=	gridExtra
R_PKGVER=	2.3

DEPENDS+=	R-gtable-[0-9]*:../../math/R-gtable

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
