# $NetBSD$

DISTNAME=	OTXv2-1.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	security python
MASTER_SITES=	${MASTER_SITE_PYPI:=O/OTXv2/}

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/AlienVault-Labs/OTX-Python-SDK
COMMENT=	Python SDK for AlienVault OTX
LICENSE=	apache-2.0

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
