# $NetBSD$

DISTNAME=	rex-java-0.1.2
CATEGORIES=	security

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/rapid7/rex-java
COMMENT=	Ruby Exploitation library for parsing Java serialized streams

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
