# $NetBSD$

DISTNAME=	rb-readline-r7-0.5.2.0
CATEGORIES=	devel

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://github.com/rapid7/rb-readline
COMMENT=	Pure Ruby implementation of the GNU readline C library
LICENSE=	bsd

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
