# $NetBSD$

CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://cran.r-project.org/package=inline
COMMENT=	Functions to inline C/C++ and Fortran function calls
LICENSE=	gnu-gpl-v2

R_PKGNAME=	inline
R_PKGVER=	0.3.14

USE_LANGUAGES=	# none

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
