# $NetBSD$

DISTNAME=	py3minepi
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}-0.0.1
CATEGORIES=	games python
MASTER_SITES=	${MASTER_SITE_GITHUB:=py3minepi/}
GITHUB_PROJECT=	py3minepi
GITHUB_TAG=	393b599fd6a9341fd4800cdd18498100dbc50d1a

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/py3minepi/py3minepi
COMMENT=	Minecraft PI Edition for Python 3

USE_LANGUAGES=	# none

EGG_NAME=	${DISTNAME}-${PKGVERSION_NOREV}

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
