# $NetBSD$

DISTNAME=	network_interface-0.0.1
CATEGORIES=	net

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/rapid7/network_interface
COMMENT=	Tool to get information on network interfaces
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
